### ISSUE TITLE
calling .validate programmaticly does nothing

### ISSUE THREAD

**Issue by Dolidodzik** [NewOldMax/react-native-validator-form#10]
I am creating register view with React Native and Expo, I also decided to use this library. It works well, but there are problem when I want to show user error in case he submit the form, API request is done and API returned message "BAD REQUEST USERNAME WAS ALREADY TAKEN". Here's the code:

Constructor:

```
   constructor(props) {
      super(props);
      // temporary state, and temporary tru register user call here
      this.state = {
         email: 'asdfasf@gmail.comwqrqwrqdas',
         username: 'fasfasfa',
         password: 'DemoPass#00',
         password_confirm: 'DemoPass#00',
         already_taken_username: "",
         username_key: 0,
      };
      this.username_input = React.createRef();
   }
```
Validation rule:

```
  Form.addValidationRule('WasUsernameTaken', (value) => {
       if (value == this.state.already_taken_username) {
         console.log("false")
         return false;
       }
       return true;
  });
```
**Code that is called when external API said username was already taken**:

```
   this.setState({
     already_taken_username: this.state.username,
     username_key: this.state.username_key++,
  })
```

  this.username_input.current.validate()
Meaningful part of render:

```
    {/* Username */}
    <TextValidator
        ref={this.username_input}
        name="username"
        label="username"
        validators={['required', 'WasUsernameTaken']}
        errorMessages={['This field is required', 'Username already taken!']}
        placeholder="Your username"
        type="text"
        value={ this.state.username }
        onChangeText={this.handleUsername}
        style = {styles.input}
        key = { this.state.username_key }
   />
```
What's the point: I excepted code that is under bold header will show user error message instantly, after calling .validate. It works only if user refresh Input mannualy (for example user first input "username", it was taken, BUT my code won't show error message. If user change "username" to "anythingelse" and then he change it again to "username", it will show error message to user as excepted).

**Comment by NewOldMax** [comment]
@Dolidodzik Hi
according source code and API doc section in readme you must pass value that must be validated to `validate` function.
So it will be `this.username_input.current.validate(this.state.username)`
