### ISSUE TITLE
Display error message when...

### ISSUE THREAD

**Issue by NewBee2014** [NewOldMax/react-native-validator-form#2]
Could we have any props to display error messages when the element passed some rules, for example: after form is submitted or some flags are turned on?

**Comment by NewOldMax** [comment]
To display messages only on submit, pass `instantValidate = false` to `ValidatorForm`. For some flags you should implement it in your input component that extends `ValidatorComponent`
````javascript
export default class TextValidator extends Input {
   render() {
      ...
     const error = this.state.isValid ? '' : this.getErrorMessage();
     //do something with this error
   }
}
````
